mysql-service:
  image: mysql:latest
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=oauth
  ports:
    - "3306:3306"
config-service:
  image: sergio11/config-service
  restart: always
  environment:
   - SPRING_PROFILES_ACTIVE=docker
  ports:
   - 8888:8888
eureka-service:
  image: sergio11/eureka-service
  restart: always
  environment:
   - SPRING_PROFILES_ACTIVE=docker
  ports:
    - 8761:8761
  links:
    - config-service
auth-service:
  image: sergio11/auth-service
  restart: always
  environment:
   - SPRING_PROFILES_ACTIVE=docker
  ports:
    - 8183:8183
  links:
    - eureka-service 
    - config-service
    - mysql-service